export const API_ENDPOINTS = {
	LOGIN: "/users/login",
	REGISTER: "/register",
	LOGOUT: "/logout",
	FORGET_PASSWORD: "/forget-password",
	CATEGORIES: "/category/get",
	// CATEGORIES: '/categories.json',
	CATEGORIES_2: "/categories.json",
	// CATEGORIES_ANCIENT: '/categories_ancient.json',
	CATEGORIES_ANCIENT: "/category/get",
	FEATURED_CATEGORIES: "/featured_categories.json",
	COLLECTIONS: "/collections.json",
	BRANDS: "/brand/get",
	// BRANDS: '/brands.json',
	BRANDS_ANCIENT: "/brands_ancient.json",
	PRODUCTS: "/product/get",
	CUSTOMPRODUCTS: "/custom-product/get",
	// PRODUCTS: '/products.json',
	PRODUCTS_2: "/product/get",
	PRODUCTS_ANCIENT: "/products_ancient.json",
	FEATURED_PRODUCTS: "/featured_products.json",
	FEATURED_PRODUCTS_ANCIENT: "/featured_products_ancient.json",
	TOP_SELLER_PRODUCTS: "/products_top_seller.json",
	ON_SELLING_PRODUCTS: "/products_on_selling.json",
	PRODUCT: "/product.json",
	RELATED_PRODUCTS: "/related_products.json",
	BEST_SELLER_PRODUCTS: "/products_best_seller.json",
	NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
	POPULAR_PRODUCTS: "/products_popular.json",
	NEW_ARRIVAL_PRODUCTS_ANCIENT: "/products_new_arrival.json",
	FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
	FLASH_SALE_PRODUCTS_ANCIENT: "/products_flash_sale_ancient.json",
	SHOPS: "/shops.json",
	SHOP: "/shop.json",
	SEARCH: "/search.json",
	ORDERS: "order/get",
	GET_USER_ORDERS: (id: string) => `order/get?userid=${id}`,
	GET_ORDER: (id: string) => `/order/get?orderid=${id}`,
	CREATE_ORDER_PAYMENT: "/order/payment/create",
	CREATE_ORDER_PHONEPAY_PAYMENT: "/order/phonepay/create",
	UPDATE_ORDER: "/order/update",
	CREATE_ORDER: "/order/create",
	VERIFY_ORDER_PAYMENT: "/order/payment/verify",
	GET_RAZORPAYKEYS: "/razorpay/getKeys",
	GET_SUBCATEGORIES: "/sub-category/get",
	GET_ACTIVE_PAYMENT_GATEWAY: "/payment-gateway/get-active",
};
