export const users = [
  {
    id: '1',
    product: 'Laptop',
    Price: '$1200',
    'Product Type': 'Electronics',
    quantity: 10,
    status: 'In Stock',
  },
  {
    id: '2',
    product: 'Smartphone',
    Price: '$800',
    'Product Type': 'Electronics',
    quantity: 25,
    status: 'Out of Stock',
  },
  {
    id: '3',
    product: 'Headphones',
    Price: '$150',
    'Product Type': 'Electronics',
    quantity: 15,
    status: 'In Stock',
  },
  {
    id: '4',
    product: 'Coffee Maker',
    Price: '$50',
    'Product Type': 'Appliances',
    quantity: 5,
    status: 'In Stock',
  },
  {
    id: '5',
    product: 'Backpack',
    Price: '$40',
    'Product Type': 'Fashion',
    quantity: 30,
    status: 'In Stock',
  },
  {
    id: '6',
    product: 'Desk Chair',
    Price: '$100',
    'Product Type': 'Furniture',
    quantity: 8,
    status: 'Out of Stock',
  },
  {
    id: '7',
    product: 'Water Bottle',
    Price: '$10',
    'Product Type': 'Home & Living',
    quantity: 50,
    status: 'In Stock',
  },
  {
    id: '8',
    product: 'Fitness Tracker',
    Price: '$80',
    'Product Type': 'Electronics',
    quantity: 12,
    status: 'In Stock',
  },
  {
    id: '9',
    product: 'Sunglasses',
    Price: '$30',
    'Product Type': 'Fashion',
    quantity: 18,
    status: 'Out of Stock',
  },
  {
    id: '10',
    product: 'Plant Pot',
    Price: '$15',
    'Product Type': 'Home & Living',
    quantity: 22,
    status: 'In Stock',
  },
  {
    id: '11',
    product: 'Wireless Mouse',
    Price: '$20',
    'Product Type': 'Electronics',
    quantity: 14,
    status: 'Out of Stock',
  },
  {
    id: '12',
    product: 'Yoga Mat',
    Price: '$25',
    'Product Type': 'Sports & Outdoors',
    quantity: 20,
    status: 'In Stock',
  },
  {
    id: '13',
    product: 'Cookware Set',
    Price: '$90',
    'Product Type': 'Appliances',
    quantity: 7,
    status: 'In Stock',
  },
  {
    id: '14',
    product: 'Bluetooth Speaker',
    Price: '$70',
    'Product Type': 'Electronics',
    quantity: 9,
    status: 'Out of Stock',
  },
  {
    id: '15',
    product: 'Wall Clock',
    Price: '$35',
    'Product Type': 'Home & Living',
    quantity: 16,
    status: 'In Stock',
  },
];
